<script lang="ts">export let size="15"; export let color="currentColor";export let ariaLabel="border none" </script><svg width="{size}" height="{size}"  class={$$props.class} {...$$restProps} aria-label={ariaLabel}  on:click on:mouseenter on:mouseleave on:mouseover on:mouseout on:blur on:focus viewBox="0 0 15 15" fill={color} xmlns="http://www.w3.org/2000/svg">
  <rect x="7" y="5.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="13" y="5.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="7" y="3.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="13" y="3.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="7" y="7.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="7" y="13.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="7" y="1.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="13" y="7.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="13" y="13.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="13" y="1.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="5" y="7.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="5" y="13.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="5" y="1.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="3" y="7.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="3" y="13.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="3" y="1.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="9" y="7.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="9" y="13.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="9" y="1.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="11" y="7.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="11" y="13.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="11" y="1.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="7" y="9.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="13" y="9.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="7" y="11.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="13" y="11.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="1" y="5.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="1" y="3.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="1" y="7.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="1" y="13.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="1" y="1.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="1" y="9.025" width="{size}" height="{size}" rx=".5"  />
  <rect x="1" y="11.025" width="{size}" height="{size}" rx=".5"  />
</svg>
