<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
</script>

<Icon.Accessibility size="40" color={random_hex_color_code()} />
<Icon.ActivityLog size="40" color={random_hex_color_code()} />
<Icon.AlignBaseline size="40" color={random_hex_color_code()} />
<Icon.AlignBottom size="40" color={random_hex_color_code()} />
<Icon.AlignCenterHorizontally size="40" color={random_hex_color_code()} />
<Icon.AlignCenterVertically size="40" color={random_hex_color_code()} />
<Icon.AlignLeft size="40" color={random_hex_color_code()} />
<Icon.AlignRight size="40" color={random_hex_color_code()} />
<Icon.AlignTop size="40" color={random_hex_color_code()} />
<Icon.AllSides size="40" color={random_hex_color_code()} />
<Icon.Angle size="40" color={random_hex_color_code()} />
<Icon.Archive size="40" color={random_hex_color_code()} />
<Icon.ArrowBottomLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowBottomRight size="40" color={random_hex_color_code()} />
<Icon.ArrowDown size="40" color={random_hex_color_code()} />
<Icon.ArrowLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowRight size="40" color={random_hex_color_code()} />
<Icon.ArrowTopLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowTopRight size="40" color={random_hex_color_code()} />
<Icon.ArrowUp size="40" color={random_hex_color_code()} />
<Icon.AspectRatio size="40" color={random_hex_color_code()} />
<Icon.Avatar size="40" color={random_hex_color_code()} />
<Icon.Backpack size="40" color={random_hex_color_code()} />
<Icon.Badge size="40" color={random_hex_color_code()} />
<Icon.BarChart size="40" color={random_hex_color_code()} />
<Icon.Bell size="40" color={random_hex_color_code()} />
<Icon.BlendingMode size="40" color={random_hex_color_code()} />
<Icon.Bookmark size="40" color={random_hex_color_code()} />
<Icon.BookmarkFilled size="40" color={random_hex_color_code()} />
<Icon.BorderAll size="40" color={random_hex_color_code()} />
<Icon.BorderBottom size="40" color={random_hex_color_code()} />
<Icon.BorderDashed size="40" color={random_hex_color_code()} />
<Icon.BorderDotted size="40" color={random_hex_color_code()} />
<Icon.BorderLeft size="40" color={random_hex_color_code()} />
<Icon.BorderNone size="40" color={random_hex_color_code()} />
<Icon.BorderRight size="40" color={random_hex_color_code()} />
<Icon.BorderSolid size="40" color={random_hex_color_code()} />
<Icon.BorderSplit size="40" color={random_hex_color_code()} />
<Icon.BorderStyle size="40" color={random_hex_color_code()} />
<Icon.BorderTop size="40" color={random_hex_color_code()} />
<Icon.BorderWidth size="40" color={random_hex_color_code()} />
<Icon.Box size="40" color={random_hex_color_code()} />
<Icon.BoxModel size="40" color={random_hex_color_code()} />
<Icon.Button size="40" color={random_hex_color_code()} />
<Icon.Calendar size="40" color={random_hex_color_code()} />
<Icon.Camera size="40" color={random_hex_color_code()} />
<Icon.CardStack size="40" color={random_hex_color_code()} />
<Icon.CardStackMinus size="40" color={random_hex_color_code()} />
<Icon.CardStackPlus size="40" color={random_hex_color_code()} />
<Icon.CaretDown size="40" color={random_hex_color_code()} />
<Icon.CaretLeft size="40" color={random_hex_color_code()} />
<Icon.CaretRight size="40" color={random_hex_color_code()} />
<Icon.CaretSort size="40" color={random_hex_color_code()} />
<Icon.CaretUp size="40" color={random_hex_color_code()} />
<Icon.ChatBubble size="40" color={random_hex_color_code()} />
<Icon.Check size="40" color={random_hex_color_code()} />
<Icon.CheckCircled size="40" color={random_hex_color_code()} />
<Icon.Checkbox size="40" color={random_hex_color_code()} />
<Icon.ChevronDown size="40" color={random_hex_color_code()} />
<Icon.ChevronLeft size="40" color={random_hex_color_code()} />
<Icon.ChevronRight size="40" color={random_hex_color_code()} />
<Icon.ChevronUp size="40" color={random_hex_color_code()} />
<Icon.Circle size="40" color={random_hex_color_code()} />
<Icon.CircleBackslash size="40" color={random_hex_color_code()} />
<Icon.Clipboard size="40" color={random_hex_color_code()} />
<Icon.ClipboardCopy size="40" color={random_hex_color_code()} />
<Icon.Clock size="40" color={random_hex_color_code()} />
<Icon.Code size="40" color={random_hex_color_code()} />
<Icon.CodesandboxLogo size="40" color={random_hex_color_code()} />
<Icon.ColorWheel size="40" color={random_hex_color_code()} />
<Icon.ColumnSpacing size="40" color={random_hex_color_code()} />
<Icon.Columns size="40" color={random_hex_color_code()} />
<Icon.Commit size="40" color={random_hex_color_code()} />
<Icon.Component1 size="40" color={random_hex_color_code()} />
<Icon.Component2 size="40" color={random_hex_color_code()} />
<Icon.ComponentBoolean size="40" color={random_hex_color_code()} />
<Icon.ComponentInstance size="40" color={random_hex_color_code()} />
<Icon.ComponentNone size="40" color={random_hex_color_code()} />
<Icon.ComponentPlaceholder size="40" color={random_hex_color_code()} />
<Icon.Container size="40" color={random_hex_color_code()} />
<Icon.Cookie size="40" color={random_hex_color_code()} />
<Icon.Copy size="40" color={random_hex_color_code()} />
<Icon.CornerBottomLeft size="40" color={random_hex_color_code()} />
<Icon.CornerBottomRight size="40" color={random_hex_color_code()} />
<Icon.CornerTopLeft size="40" color={random_hex_color_code()} />
<Icon.CornerTopRight size="40" color={random_hex_color_code()} />
<Icon.Corners size="40" color={random_hex_color_code()} />
<Icon.CountdownTimer size="40" color={random_hex_color_code()} />
<Icon.CounterClockwiseClock size="40" color={random_hex_color_code()} />
<Icon.Crop size="40" color={random_hex_color_code()} />
<Icon.Cross1 size="40" color={random_hex_color_code()} />
<Icon.Cross2 size="40" color={random_hex_color_code()} />
<Icon.CrossCircled size="40" color={random_hex_color_code()} />
<Icon.Crosshair1 size="40" color={random_hex_color_code()} />
<Icon.Crosshair2 size="40" color={random_hex_color_code()} />
<Icon.CrumpledPaper size="40" color={random_hex_color_code()} />
<Icon.Cube size="40" color={random_hex_color_code()} />
<Icon.CursorArrow size="40" color={random_hex_color_code()} />
<Icon.CursorText size="40" color={random_hex_color_code()} />
<Icon.Dash size="40" color={random_hex_color_code()} />
<Icon.Dashboard size="40" color={random_hex_color_code()} />
<Icon.Desktop size="40" color={random_hex_color_code()} />
<Icon.Dimensions size="40" color={random_hex_color_code()} />
<Icon.Disc size="40" color={random_hex_color_code()} />
<Icon.DiscordLogo size="40" color={random_hex_color_code()} />
<Icon.DividerHorizontal size="40" color={random_hex_color_code()} />
<Icon.DividerVertical size="40" color={random_hex_color_code()} />
<Icon.Dot size="40" color={random_hex_color_code()} />
<Icon.DotFilled size="40" color={random_hex_color_code()} />
<Icon.DotsHorizontal size="40" color={random_hex_color_code()} />
<Icon.DotsVertical size="40" color={random_hex_color_code()} />
<Icon.DoubleArrowDown size="40" color={random_hex_color_code()} />
<Icon.DoubleArrowLeft size="40" color={random_hex_color_code()} />
<Icon.DoubleArrowRight size="40" color={random_hex_color_code()} />
<Icon.DoubleArrowUp size="40" color={random_hex_color_code()} />
<Icon.Download size="40" color={random_hex_color_code()} />
<Icon.DragHandleDots1 size="40" color={random_hex_color_code()} />
<Icon.DragHandleDots2 size="40" color={random_hex_color_code()} />
<Icon.DragHandleHorizontal size="40" color={random_hex_color_code()} />
<Icon.DragHandleVertical size="40" color={random_hex_color_code()} />
<Icon.DrawingPin size="40" color={random_hex_color_code()} />
<Icon.DrawingPinFilled size="40" color={random_hex_color_code()} />
<Icon.DropdownMenu size="40" color={random_hex_color_code()} />
<Icon.Enter size="40" color={random_hex_color_code()} />
<Icon.EnterFullScreen size="40" color={random_hex_color_code()} />
<Icon.EnvelopeClosed size="40" color={random_hex_color_code()} />
<Icon.EnvelopeOpen size="40" color={random_hex_color_code()} />
<Icon.Eraser size="40" color={random_hex_color_code()} />
<Icon.ExclamationTriangle size="40" color={random_hex_color_code()} />
<Icon.Exit size="40" color={random_hex_color_code()} />
<Icon.ExitFullScreen size="40" color={random_hex_color_code()} />
<Icon.ExternalLink size="40" color={random_hex_color_code()} />
<Icon.EyeClosed size="40" color={random_hex_color_code()} />
<Icon.EyeNone size="40" color={random_hex_color_code()} />
<Icon.EyeOpen size="40" color={random_hex_color_code()} />
<Icon.Face size="40" color={random_hex_color_code()} />
<Icon.FigmaLogo size="40" color={random_hex_color_code()} />
<Icon.File size="40" color={random_hex_color_code()} />
<Icon.FileMinus size="40" color={random_hex_color_code()} />
<Icon.FilePlus size="40" color={random_hex_color_code()} />
<Icon.FileText size="40" color={random_hex_color_code()} />
<Icon.FontBold size="40" color={random_hex_color_code()} />
<Icon.FontFamily size="40" color={random_hex_color_code()} />
<Icon.FontItalic size="40" color={random_hex_color_code()} />
<Icon.FontRoman size="40" color={random_hex_color_code()} />
<Icon.FontSize size="40" color={random_hex_color_code()} />
<Icon.FontStyle size="40" color={random_hex_color_code()} />
<Icon.Frame size="40" color={random_hex_color_code()} />
<Icon.FramerLogo size="40" color={random_hex_color_code()} />
<Icon.Gear size="40" color={random_hex_color_code()} />
<Icon.GithubLogo size="40" color={random_hex_color_code()} />
<Icon.Globe size="40" color={random_hex_color_code()} />
<Icon.Grid size="40" color={random_hex_color_code()} />
<Icon.Group size="40" color={random_hex_color_code()} />
<Icon.Half1 size="40" color={random_hex_color_code()} />
<Icon.Half2 size="40" color={random_hex_color_code()} />
<Icon.HamburgerMenu size="40" color={random_hex_color_code()} />
<Icon.Hand size="40" color={random_hex_color_code()} />
<Icon.Heading size="40" color={random_hex_color_code()} />
<Icon.Heart size="40" color={random_hex_color_code()} />
<Icon.HeartFilled size="40" color={random_hex_color_code()} />
<Icon.Height size="40" color={random_hex_color_code()} />
<Icon.HobbyKnife size="40" color={random_hex_color_code()} />
<Icon.Home size="40" color={random_hex_color_code()} />
<Icon.IconjarLogo size="40" color={random_hex_color_code()} />
<Icon.IdCard size="40" color={random_hex_color_code()} />
<Icon.Image size="40" color={random_hex_color_code()} />
<Icon.InfoCircled size="40" color={random_hex_color_code()} />
<Icon.Input size="40" color={random_hex_color_code()} />
<Icon.InstagramLogo size="40" color={random_hex_color_code()} />
<Icon.Keyboard size="40" color={random_hex_color_code()} />
<Icon.LapTimer size="40" color={random_hex_color_code()} />
<Icon.Laptop size="40" color={random_hex_color_code()} />
<Icon.Layers size="40" color={random_hex_color_code()} />
<Icon.Layout size="40" color={random_hex_color_code()} />
<Icon.LetterCaseCapitalize size="40" color={random_hex_color_code()} />
<Icon.LetterCaseLowercase size="40" color={random_hex_color_code()} />
<Icon.LetterCaseToggle size="40" color={random_hex_color_code()} />
<Icon.LetterCaseUppercase size="40" color={random_hex_color_code()} />
<Icon.LetterSpacing size="40" color={random_hex_color_code()} />
<Icon.LightningBolt size="40" color={random_hex_color_code()} />
<Icon.LineHeight size="40" color={random_hex_color_code()} />
<Icon.Link1 size="40" color={random_hex_color_code()} />
<Icon.Link2 size="40" color={random_hex_color_code()} />
<Icon.LinkBreak1 size="40" color={random_hex_color_code()} />
<Icon.LinkBreak2 size="40" color={random_hex_color_code()} />
<Icon.LinkNone1 size="40" color={random_hex_color_code()} />
<Icon.LinkNone2 size="40" color={random_hex_color_code()} />
<Icon.LinkedinLogo size="40" color={random_hex_color_code()} />
<Icon.ListBullet size="40" color={random_hex_color_code()} />
<Icon.LockClosed size="40" color={random_hex_color_code()} />
<Icon.LockOpen1 size="40" color={random_hex_color_code()} />
<Icon.LockOpen2 size="40" color={random_hex_color_code()} />
<Icon.Loop size="40" color={random_hex_color_code()} />
<Icon.MagicWand size="40" color={random_hex_color_code()} />
<Icon.MagnifyingGlass size="40" color={random_hex_color_code()} />
<Icon.Margin size="40" color={random_hex_color_code()} />
<Icon.MaskOff size="40" color={random_hex_color_code()} />
<Icon.MaskOn size="40" color={random_hex_color_code()} />
<Icon.Minus size="40" color={random_hex_color_code()} />
<Icon.MinusCircled size="40" color={random_hex_color_code()} />
<Icon.Mix size="40" color={random_hex_color_code()} />
<Icon.MixerHorizontal size="40" color={random_hex_color_code()} />
<Icon.MixerVertical size="40" color={random_hex_color_code()} />
<Icon.Mobile size="40" color={random_hex_color_code()} />
<Icon.ModulzLogo size="40" color={random_hex_color_code()} />
<Icon.Moon size="40" color={random_hex_color_code()} />
<Icon.Move size="40" color={random_hex_color_code()} />
<Icon.NotionLogo size="40" color={random_hex_color_code()} />
<Icon.Opacity size="40" color={random_hex_color_code()} />
<Icon.OpenInNewWindow size="40" color={random_hex_color_code()} />
<Icon.Overline size="40" color={random_hex_color_code()} />
<Icon.Padding size="40" color={random_hex_color_code()} />
<Icon.PaperPlane size="40" color={random_hex_color_code()} />
<Icon.Pause size="40" color={random_hex_color_code()} />
<Icon.Pencil1 size="40" color={random_hex_color_code()} />
<Icon.Pencil2 size="40" color={random_hex_color_code()} />
<Icon.Person size="40" color={random_hex_color_code()} />
<Icon.PieChart size="40" color={random_hex_color_code()} />
<Icon.Pilcrow size="40" color={random_hex_color_code()} />
<Icon.PinBottom size="40" color={random_hex_color_code()} />
<Icon.PinLeft size="40" color={random_hex_color_code()} />
<Icon.PinRight size="40" color={random_hex_color_code()} />
<Icon.PinTop size="40" color={random_hex_color_code()} />
<Icon.Play size="40" color={random_hex_color_code()} />
<Icon.Plus size="40" color={random_hex_color_code()} />
<Icon.PlusCircled size="40" color={random_hex_color_code()} />
<Icon.QuestionMark size="40" color={random_hex_color_code()} />
<Icon.QuestionMarkCircled size="40" color={random_hex_color_code()} />
<Icon.Quote size="40" color={random_hex_color_code()} />
<Icon.Radiobutton size="40" color={random_hex_color_code()} />
<Icon.Reader size="40" color={random_hex_color_code()} />
<Icon.Reload size="40" color={random_hex_color_code()} />
<Icon.Reset size="40" color={random_hex_color_code()} />
<Icon.Resume size="40" color={random_hex_color_code()} />
<Icon.Rocket size="40" color={random_hex_color_code()} />
<Icon.RotateCounterClockwise size="40" color={random_hex_color_code()} />
<Icon.RowSpacing size="40" color={random_hex_color_code()} />
<Icon.Rows size="40" color={random_hex_color_code()} />
<Icon.RulerHorizontal size="40" color={random_hex_color_code()} />
<Icon.RulerSquare size="40" color={random_hex_color_code()} />
<Icon.Scissors size="40" color={random_hex_color_code()} />
<Icon.Section size="40" color={random_hex_color_code()} />
<Icon.SewingPin size="40" color={random_hex_color_code()} />
<Icon.SewingPinFilled size="40" color={random_hex_color_code()} />
<Icon.Shadow size="40" color={random_hex_color_code()} />
<Icon.ShadowInner size="40" color={random_hex_color_code()} />
<Icon.ShadowNone size="40" color={random_hex_color_code()} />
<Icon.ShadowOuter size="40" color={random_hex_color_code()} />
<Icon.Share1 size="40" color={random_hex_color_code()} />
<Icon.Share2 size="40" color={random_hex_color_code()} />
<Icon.Shuffle size="40" color={random_hex_color_code()} />
<Icon.Size size="40" color={random_hex_color_code()} />
<Icon.SketchLogo size="40" color={random_hex_color_code()} />
<Icon.Slash size="40" color={random_hex_color_code()} />
<Icon.Slider size="40" color={random_hex_color_code()} />
<Icon.SpaceBetweenHorizontally size="40" color={random_hex_color_code()} />
<Icon.SpaceBetweenVertically size="40" color={random_hex_color_code()} />
<Icon.SpaceEvenlyHorizontally size="40" color={random_hex_color_code()} />
<Icon.SpaceEvenlyVertically size="40" color={random_hex_color_code()} />
<Icon.SpeakerLoud size="40" color={random_hex_color_code()} />
<Icon.SpeakerModerate size="40" color={random_hex_color_code()} />
<Icon.SpeakerOff size="40" color={random_hex_color_code()} />
<Icon.SpeakerQuiet size="40" color={random_hex_color_code()} />
<Icon.Square size="40" color={random_hex_color_code()} />
<Icon.Stack size="40" color={random_hex_color_code()} />
<Icon.Star size="40" color={random_hex_color_code()} />
<Icon.StarFilled size="40" color={random_hex_color_code()} />
<Icon.StitchesLogo size="40" color={random_hex_color_code()} />
<Icon.Stop size="40" color={random_hex_color_code()} />
<Icon.Stopwatch size="40" color={random_hex_color_code()} />
<Icon.StretchHorizontally size="40" color={random_hex_color_code()} />
<Icon.StretchVertically size="40" color={random_hex_color_code()} />
<Icon.Strikethrough size="40" color={random_hex_color_code()} />
<Icon.Sun size="40" color={random_hex_color_code()} />
<Icon.Switch size="40" color={random_hex_color_code()} />
<Icon.Symbol size="40" color={random_hex_color_code()} />
<Icon.Table size="40" color={random_hex_color_code()} />
<Icon.Target size="40" color={random_hex_color_code()} />
<Icon.Text size="40" color={random_hex_color_code()} />
<Icon.TextAlignBottom size="40" color={random_hex_color_code()} />
<Icon.TextAlignCenter size="40" color={random_hex_color_code()} />
<Icon.TextAlignJustify size="40" color={random_hex_color_code()} />
<Icon.TextAlignLeft size="40" color={random_hex_color_code()} />
<Icon.TextAlignMiddle size="40" color={random_hex_color_code()} />
<Icon.TextAlignRight size="40" color={random_hex_color_code()} />
<Icon.TextAlignTop size="40" color={random_hex_color_code()} />
<Icon.TextNone size="40" color={random_hex_color_code()} />
<Icon.ThickArrowDown size="40" color={random_hex_color_code()} />
<Icon.ThickArrowLeft size="40" color={random_hex_color_code()} />
<Icon.ThickArrowRight size="40" color={random_hex_color_code()} />
<Icon.ThickArrowUp size="40" color={random_hex_color_code()} />
<Icon.Timer size="40" color={random_hex_color_code()} />
<Icon.Tokens size="40" color={random_hex_color_code()} />
<Icon.TrackNext size="40" color={random_hex_color_code()} />
<Icon.TrackPrevious size="40" color={random_hex_color_code()} />
<Icon.Transform size="40" color={random_hex_color_code()} />
<Icon.TransparencyGrid size="40" color={random_hex_color_code()} />
<Icon.Trash size="40" color={random_hex_color_code()} />
<Icon.TriangleDown size="40" color={random_hex_color_code()} />
<Icon.TriangleLeft size="40" color={random_hex_color_code()} />
<Icon.TriangleRight size="40" color={random_hex_color_code()} />
<Icon.TriangleUp size="40" color={random_hex_color_code()} />
<Icon.TwitterLogo size="40" color={random_hex_color_code()} />
<Icon.Underline size="40" color={random_hex_color_code()} />
<Icon.Update size="40" color={random_hex_color_code()} />
<Icon.Upload size="40" color={random_hex_color_code()} />
<Icon.Value size="40" color={random_hex_color_code()} />
<Icon.ValueNone size="40" color={random_hex_color_code()} />
<Icon.VercelLogo size="40" color={random_hex_color_code()} />
<Icon.Video size="40" color={random_hex_color_code()} />
<Icon.ViewGrid size="40" color={random_hex_color_code()} />
<Icon.ViewHorizontal size="40" color={random_hex_color_code()} />
<Icon.ViewNone size="40" color={random_hex_color_code()} />
<Icon.ViewVertical size="40" color={random_hex_color_code()} />
<Icon.Width size="40" color={random_hex_color_code()} />
<Icon.ZoomIn size="40" color={random_hex_color_code()} />
<Icon.ZoomOut size="40" color={random_hex_color_code()} />
